In [ ]:
#nhận diện mạng có chữ dùng convolution  , use Conv1D

In [ ]:
!wget --no-check-certificate \https://storage.googleapis.com/laurencemoroney-blog.appspot.com/sarcasm.json \-O /tmp/sarcasm.json

--2020-07-06 02:36:26--  https://storage.googleapis.com/laurencemoroney-blog.appspot.com/sarcasm.json
Resolving storage.googleapis.com (storage.googleapis.com)... 64.233.167.128, 74.125.133.128, 173.194.76.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|64.233.167.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5643545 (5.4M) [application/json]
Saving to: ‘/tmp/sarcasm.json’

/tmp/sarcasm.json   100%[===================>]   5.38M  --.-KB/s    in 0.05s   

2020-07-06 02:36:26 (100 MB/s) - ‘/tmp/sarcasm.json’ saved [5643545/5643545]



In [ ]:
import json # laf files json . csv thi dung pandas cat

In [ ]:
#đọc data mỉa mai (sarcastic)
with open("/tmp/sarcasm.json","r")as f:
  data = json.load(f)

In [ ]:
data[20] # 1 là mỉa mai , 0 là không mỉa mai .

{'article_link': 'https://local.theonion.com/courtroom-sketch-artist-has-clear-manga-influences-1820298494',
 'headline': 'courtroom sketch artist has clear manga influences',
 'is_sarcastic': 1}

In [ ]:
sentences = []
labels = []
#lay tu , để tạo từ điển để có EB
for item in data:
  sentences.append(item["headline"])
  labels.append(item["is_sarcastic"])

NameError: ignored

In [ ]:
len(sentences)# so cau

26709

In [ ]:
len(labels)

26709

In [ ]:
train_size = 20000 

In [ ]:
train_sentences = sentences[:train_size]
train_labels = labels[:train_size]
test_sentences= sentences[train_size:]
test_labels = labels[train_size:]

In [ ]:
#chuyển thành numpy
import numpy as np 
train_labels = np.array(train_labels)
test_labels = np.array(test_labels)

In [ ]:
train_labels

array([0, 0, 1, ..., 0, 0, 1])

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer # Tach cac tu 
from tensorflow.keras.preprocessing.sequence import pad_sequences 

In [ ]:
vocab_size = 10000 # sẽ ảnh hưởng tới EB , số lượng từ ít , vocab ít thui

In [ ]:
tokenizer = Tokenizer(num_words=vocab_size,oov_token="<OOV>") # one hot 6 thì vecter từ ở vị trí thứ 6 , oov là 1 thì vị trí là 1


In [ ]:
tokenizer.fit_on_texts(train_sentences)

In [ ]:
tokenizer.word_index #Số lần xuất hiện từ , những số này sẽ ảnh hướng tới one hot .

{'<OOV>': 1,
 'to': 2,
 'of': 3,
 'the': 4,
 'in': 5,
 'for': 6,
 'a': 7,
 'on': 8,
 'and': 9,
 'with': 10,
 'is': 11,
 'new': 12,
 'trump': 13,
 'man': 14,
 'from': 15,
 'at': 16,
 'about': 17,
 'you': 18,
 'by': 19,
 'this': 20,
 'after': 21,
 'be': 22,
 'up': 23,
 'out': 24,
 'that': 25,
 'how': 26,
 'as': 27,
 'it': 28,
 'not': 29,
 'are': 30,
 'your': 31,
 'what': 32,
 'his': 33,
 'all': 34,
 'he': 35,
 'will': 36,
 'who': 37,
 'just': 38,
 'has': 39,
 'more': 40,
 'one': 41,
 'year': 42,
 'into': 43,
 'report': 44,
 'have': 45,
 'why': 46,
 'over': 47,
 'area': 48,
 'u': 49,
 'donald': 50,
 'says': 51,
 'day': 52,
 'can': 53,
 's': 54,
 'first': 55,
 'woman': 56,
 'time': 57,
 'like': 58,
 'get': 59,
 'old': 60,
 'no': 61,
 'her': 62,
 "trump's": 63,
 'off': 64,
 'now': 65,
 'an': 66,
 'obama': 67,
 'life': 68,
 'people': 69,
 'women': 70,
 'house': 71,
 "'": 72,
 'was': 73,
 'still': 74,
 'white': 75,
 'back': 76,
 'make': 77,
 'than': 78,
 'clinton': 79,
 'down': 80,
 'when': 8

In [ ]:
train_sentences = tokenizer.texts_to_sequences(train_sentences)# áp dụng tokenizer vào các câu , lưu ý oov là :1

In [ ]:
#train_sentences[0]
print(train_sentences[0],type(train_sentences))

[328, 1, 799, 3405, 2404, 47, 389, 2214, 1, 6, 2614, 8863] <class 'list'>


In [ ]:
test_sentences = tokenizer.texts_to_sequences(test_sentences)

In [ ]:
max_length = 140 
padded_train_sequences= pad_sequences(train_sentences,
                                      maxlen= max_length,
                                      padding='post',
                                      truncating='post') # Cắt câu hơn 140 từ thì sẽ cắt , ngắn hơn 140  thì sẽ padding thành ma trận , từ nào ko có sẽ thành 0 

In [ ]:
#Rồi đưa vào từ điển

In [ ]:
padded_train_sequences.shape

(20000, 140)

In [ ]:
padded_train_sequences

array([[ 328,    1,  799, ...,    0,    0,    0],
       [   4, 6840, 3096, ...,    0,    0,    0],
       [ 153,  890,    2, ...,    0,    0,    0],
       ...,
       [  79, 1729,    1, ...,    0,    0,    0],
       [  53, 5108, 4735, ...,    0,    0,    0],
       [ 312,  705,    1, ...,    0,    0,    0]], dtype=int32)

In [ ]:
padded_test_sequences= pad_sequences(test_sentences,
                                      maxlen= max_length,
                                      padding='post',
                                      truncating='post')

In [ ]:
#Hoàn thành tạo từ điển thành ma trận.

In [ ]:
padded_test_sequences.shape

(6709, 140)

In [ ]:
from tensorflow.keras.models import  Sequential
from tensorflow.keras.layers  import GlobalAveragePooling1D
from tensorflow.keras.layers  import Dense
from tensorflow.keras.layers import Conv1D # thường những bài toán về timeseries thì Conv1D dùng rất là nhiều
from tensorflow.keras.layers import Embedding # chỉ là 1 ma trận thôi

In [ ]:
model = Sequential()
model.add(Embedding(vocab_size,64)) # 64 là chiều vecter
model.add(Conv1D(128,5,activation='relu'))  #1 từ là 64x1 . Conv sẽ là 5x1 chạy trên 1 từ (64x1)
model.add(GlobalAveragePooling1D())
model.add(Dense(64,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 64)          640000    
_________________________________________________________________
conv1d_2 (Conv1D)            (None, None, 128)         41088     
_________________________________________________________________
global_average_pooling1d_1 ( (None, 128)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 65        
Total params: 689,409
Trainable params: 689,409
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(loss = 'binary_crossentropy',optimizer='adam',metrics='acc')
model.fit(padded_train_sequences,train_labels, 
          epochs=10,
          validation_data=(padded_test_sequences,test_labels))

Epoch 1/15
625/625 [==============================] - 8s 12ms/step - loss: 0.4595 - acc: 0.7655 - val_loss: 0.3563 - val_acc: 0.8430
Epoch 2/15
625/625 [==============================] - 8s 12ms/step - loss: 0.2410 - acc: 0.9026 - val_loss: 0.3468 - val_acc: 0.8557
Epoch 3/15
625/625 [==============================] - 8s 12ms/step - loss: 0.1545 - acc: 0.9420 - val_loss: 0.4028 - val_acc: 0.8474
Epoch 4/15
625/625 [==============================] - 8s 13ms/step - loss: 0.0935 - acc: 0.9670 - val_loss: 0.5229 - val_acc: 0.8395
Epoch 5/15
625/625 [==============================] - 8s 12ms/step - loss: 0.0512 - acc: 0.9834 - val_loss: 0.6246 - val_acc: 0.8350
Epoch 6/15
625/625 [==============================] - 8s 12ms/step - loss: 0.0288 - acc: 0.9917 - val_loss: 0.7520 - val_acc: 0.8286
Epoch 7/15
625/625 [==============================] - 8s 12ms/step - loss: 0.0143 - acc: 0.9960 - val_loss: 0.8529 - val_acc: 0.8305
Epoch 8/15
625/625 [==============================] - 8s 12ms/step - 

In [ ]:
#predict
test= [
      test_sentences[74],
      test_sentences[100],
       test_sentences[5000]
]

In [ ]:
print(test_labels[74],
      test_labels[100],
       test_labels[5000])

0 1 1


In [ ]:
test_sequences = tokenizer.texts_to_sequences(test) 

In [ ]:
pad_test_sequences = pad_sequences(test_sequences,
                                      maxlen= 140,
                                      padding='post',
                                      truncating='post')

In [ ]:
model.predict(pad_test_sequences).round()

array([[1.],
       [0.],
       [1.]], dtype=float32)

In [ ]:

from tensorflow.keras.layers import Bidirectional 
from tensorflow.keras.layers import  LSTM
from tensorflow.keras.layers import  GRU

In [ ]:
model2 = Sequential()
model2.add(Embedding(vocab_size, 64))
model2.add(Bidirectional(LSTM(64, return_sequences=True)))
model2.add(Bidirectional(LSTM(32)))
model2.add(Dense(64, activation='relu'))
model2.add(Dense(1, activation='sigmoid'))

In [ ]:
model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 64)          640000    
_________________________________________________________________
bidirectional (Bidirectional (None, None, 128)         66048     
_________________________________________________________________
bidirectional_1 (Bidirection (None, 64)                41216     
_________________________________________________________________
dense (Dense)                (None, 64)                4160      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
Total params: 751,489
Trainable params: 751,489
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model2.compile(loss = 'binary_crossentropy',optimizer='adam',metrics='acc')
model2.fit(padded_train_sequences,train_labels, 
          epochs=15,
          validation_data=(padded_test_sequences,test_labels))

Epoch 1/15
625/625 [==============================] - 21s 33ms/step - loss: 0.3851 - acc: 0.8162 - val_loss: 0.3205 - val_acc: 0.8612
Epoch 2/15
625/625 [==============================] - 20s 31ms/step - loss: 0.1879 - acc: 0.9254 - val_loss: 0.3521 - val_acc: 0.8551
Epoch 3/15
625/625 [==============================] - 20s 31ms/step - loss: 0.1027 - acc: 0.9633 - val_loss: 0.4468 - val_acc: 0.8408
Epoch 4/15
625/625 [==============================] - 20s 31ms/step - loss: 0.0604 - acc: 0.9796 - val_loss: 0.5619 - val_acc: 0.8399
Epoch 5/15
625/625 [==============================] - 19s 31ms/step - loss: 0.0392 - acc: 0.9872 - val_loss: 0.6442 - val_acc: 0.8399
Epoch 6/15
625/625 [==============================] - 20s 31ms/step - loss: 0.0264 - acc: 0.9916 - val_loss: 0.8265 - val_acc: 0.8331
Epoch 7/15
625/625 [==============================] - 20s 32ms/step - loss: 0.0186 - acc: 0.9940 - val_loss: 0.8926 - val_acc: 0.8328
Epoch 8/15
625/625 [==============================] - 19s 31ms

In [ ]:
#predict
model2.predict(pad_test_sequences).round()

array([[0.],
       [0.],
       [0.]], dtype=float32)