#### Mục tiêu: Xây dựng mô hình có độ chính xác trên tập validation khoảng 87%

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalAveragePooling1D

In [3]:

import tensorflow as tf

import tensorflow_datasets as tfds
imdb, info = tfds.load("imdb_reviews/subwords8k", with_info=True, as_supervised=True)

Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incompleteGFCVAU/imdb_reviews-train.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incompleteGFCVAU/imdb_reviews-test.tfrecord


Shuffling and writing examples to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0.incompleteGFCVAU/imdb_reviews-unsupervised.tfrecord


Dataset imdb_reviews downloaded and prepared to /root/tensorflow_datasets/imdb_reviews/subwords8k/1.0.0. Subsequent calls will reuse this data.


In [4]:
train_data, test_data = imdb['train'], imdb['test']

In [5]:
tokenizer = info.features['text'].encoder

In [6]:
train_data = train_data.padded_batch(64, train_data.output_shapes)
test_data = test_data.padded_batch(64, test_data.output_shapes)

Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(dataset)`.


Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(dataset)`.


In [7]:
for item in train_data:
  print(item)

(<tf.Tensor: shape=(64, 1109), dtype=int64, numpy=
array([[  62,   18,   41, ...,    0,    0,    0],
       [  12,   31,   93, ...,    0,    0,    0],
       [ 636,  102, 4714, ...,    0,    0,    0],
       ...,
       [ 133, 1955,    5, ...,    0,    0,    0],
       [2635, 1610,   48, ...,    0,    0,    0],
       [  12,  196, 7968, ...,    0,    0,    0]])>, <tf.Tensor: shape=(64,), dtype=int64, numpy=
array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1])>)
(<tf.Tensor: shape=(64, 1179), dtype=int64, numpy=
array([[3943,    4,  848, ...,    0,    0,    0],
       [1646, 1760,  463, ...,    0,    0,    0],
       [1993,   38,  601, ...,    0,    0,    0],
       ...,
       [  12,   81,  196, ...,    0,    0,    0],
       [3404, 5426, 7961, ...,    0,    0,    0],
       [ 156,    1, 4030, ...,    0,    0,    0]])>, <tf.Ten

In [9]:
# Xây dựng model
from tensorflow.keras.layers import  Conv1D
# FIXME: Tạo model Sequential

model = Sequential()

# FIXME: Thêm một lớp Embedding

model.add((Embedding(input_dim=tokenizer.vocab_size, output_dim=64)))
model.add(Conv1D(128,5,activation='relu'))

model.add(GlobalAveragePooling1D()) # Ta hoàn toàn có thể sử dụng một lớp Convolution 1D sau embedding để tìm mối quan hệ giữa các từ

# FIXME: Thêm một lớp Dense, chú ý có activation

model.add(Dense(64,activation="relu"))

# FIXME: Thêm một lớp Dense cuối, chú ý có activation

model.add(Dense(1,activation="sigmoid"))


In [10]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, None, 64)          523840    
_________________________________________________________________
conv1d (Conv1D)              (None, None, 128)         41088     
_________________________________________________________________
global_average_pooling1d (Gl (None, 128)               0         
_________________________________________________________________
dense (Dense)                (None, 64)                8256      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
Total params: 573,249
Trainable params: 573,249
Non-trainable params: 0
_________________________________________________________________


In [15]:
num_epochs = 10

# FIXME: Compile Optimizer và Loss function

model.compile(loss = 'binary_crossentropy',optimizer='adam',metrics='acc')

# FIXME: Tiến hành training. Mục tiêu: 87 %

history = model.fit(train_data, 
          epochs=num_epochs,
          validation_data=(test_data))

Epoch 1/10
391/391 [==============================] - 245s 626ms/step - loss: 0.4467 - acc: 0.7772 - val_loss: 0.3130 - val_acc: 0.8756
Epoch 2/10
391/391 [==============================] - 245s 626ms/step - loss: 0.2260 - acc: 0.9152 - val_loss: 0.3108 - val_acc: 0.8795
Epoch 3/10
391/391 [==============================] - 244s 625ms/step - loss: 0.1727 - acc: 0.9370 - val_loss: 0.3440 - val_acc: 0.8760
Epoch 4/10
391/391 [==============================] - 242s 619ms/step - loss: 0.1427 - acc: 0.9495 - val_loss: 0.4070 - val_acc: 0.8628
Epoch 5/10
391/391 [==============================] - 242s 620ms/step - loss: 0.1256 - acc: 0.9554 - val_loss: 0.4422 - val_acc: 0.8575
Epoch 6/10
391/391 [==============================] - 242s 620ms/step - loss: 0.1129 - acc: 0.9584 - val_loss: 0.4971 - val_acc: 0.8617
Epoch 7/10
391/391 [==============================] - 242s 620ms/step - loss: 0.1054 - acc: 0.9613 - val_loss: 0.5694 - val_acc: 0.8570
Epoch 8/10
391/391 [============================

In [19]:
print('the best : ',max(history.history['val_acc']))

the best :  0.8795199990272522
