In [ ]:
from __future__ import absolute_import, division, print_function, unicode_literals

# Install TensorFlow

import tensorflow as tf

In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
from tensorflow.keras import datasets
# TensorFlow and tf.keras
import tensorflow as tf
from tensorflow import keras

# Helper libraries
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
fashion_mnist = keras.datasets.fashion_mnist

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

4423680/4422102 [==============================] - 0s 0us/step


In [ ]:
y_train.shape

(60000,)

In [ ]:
x_train.shape # kiểm tra shape , xem có thiếu chanel ko ?

(60000, 28, 28)

In [ ]:
x_train = tf.reshape(x_train,(60000,28,28,1))

In [ ]:
x_train.shape

TensorShape([60000, 28, 28, 1])

In [ ]:
x_train = x_train[:,:,:,np.newaxis]

In [ ]:
x_train.shape

TensorShape([60000, 28, 28, 1, 1])

In [ ]:
x_test = x_test[:,:,:,np.newaxis]

In [ ]:
x_test.shape

(10000, 28, 28, 1)

In [ ]:
x_train.shape

(60000, 28, 28, 1)

In [ ]:
num_classes = 10

In [ ]:
from tensorflow.keras.utils import  to_categorical # chuyeern one hot ko can dung spa lan trc hoc paas1

In [ ]:
y_train = to_categorical(y_train,num_classes)
y_train.shape # ddaay la one hot

(60000, 10)

In [ ]:
y_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
one_hot = [[0 for _ in range(num_classes)]for _ in range(len(y_train)) ]

In [ ]:
for i in range(len(one_hot)):
  one_hot[i][y_train[i]] = 1

In [ ]:
y_train

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
x_train = x_train.astype('float32')
x_test  = x_test.astype('float32')

In [ ]:
x_train = x_train / 255.0
x_test = x_test /255.0

In [ ]:
model   = Sequential()                                            

In [ ]:
from tensorflow.keras.layers import Conv2D
#conv

In [ ]:
model.add(Conv2D(6,kernel_size=(5,5),strides=1,activation='relu',input_shape= [28,28,1],padding='same'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 28, 28, 6)         156       
Total params: 156
Trainable params: 156
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#
from tensorflow.keras.layers import AveragePooling2D

In [ ]:
model.add(AveragePooling2D(pool_size=(2,2),strides=(2,2)))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 28, 28, 6)         156       
_________________________________________________________________
average_pooling2d (AveragePo (None, 14, 14, 6)         0         
Total params: 156
Trainable params: 156
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.add(Conv2D(16,kernel_size=(5,5),strides = (1,1),activation='relu'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 28, 28, 6)         156       
_________________________________________________________________
average_pooling2d (AveragePo (None, 14, 14, 6)         0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 10, 10, 16)        2416      
Total params: 2,572
Trainable params: 2,572
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.add(AveragePooling2D(pool_size=(2,2),strides=(2,2)))

In [ ]:
from tensorflow.keras.layers import Flatten

In [ ]:
model.add(Flatten())

In [ ]:
from tensorflow.keras.layers import Dense

In [ ]:
model.add(Dense(120,activation='relu'))

In [ ]:
model.add(Dense(84,activation='relu'))

In [ ]:
model.add(Dense(10,activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_4 (Conv2D)            (None, 28, 28, 6)         156       
_________________________________________________________________
average_pooling2d (AveragePo (None, 14, 14, 6)         0         
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 10, 10, 16)        2416      
_________________________________________________________________
average_pooling2d_1 (Average (None, 5, 5, 16)          0         
_________________________________________________________________
flatten (Flatten)            (None, 400)               0         
_________________________________________________________________
dense (Dense)                (None, 120)               48120     
_________________________________________________________________
dense_1 (Dense)              (None, 84)               

In [ ]:
model.compile(optimizer='SGD',loss = 'categorical_crossentropy',metrics = ['acc'])

In [ ]:
expected_acc = 0.9
# tính đa hình , kế thừa tạo ra 1 hàm mới
# đ/n 1 calss kế thừa clss kia
class MyCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self,epoch,logs=()):
    if(logs.get('acc') > expected_acc):
      self.model.stop_training =True


In [ ]:
callbacks = MyCallback()

In [ ]:
x_train.shape # ktra lai chuan hoa chua

(60000, 28, 28, 1)

In [ ]:
model.fit(x_train,y_train,epochs =11 ,verbose =1,callbacks=[callbacks] )

Epoch 1/11
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2800 - acc: 0.8963
Epoch 2/11
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2751 - acc: 0.8982
Epoch 3/11
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2711 - acc: 0.8995
Epoch 4/11
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2669 - acc: 0.9014


In [ ]:
#predict
test_image = x_test[0]


In [ ]:
test_image.shape

(28, 28, 1)

In [ ]:
test_image= tf.reshape(test_image,(1,28,28,1))
test_image = test_image*255.0
test_image.shape

TensorShape([1, 28, 28, 1])

In [ ]:
model.predict(test_image)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)

In [ ]:
result = np.argmax(model.predict(test_image))

In [ ]:
result

9